### ISSUE TITLE
git xl is not a git command

### ISSUE THREAD

**Issue by CharlesRHall** [xlwings/git-xl#50]
I am running win 7, downloaded the git-xl-windows-0.4.1.exe file, and installed it.

However when I try to install xl in git with
git xl install

I get the error
git: 'xl' is not a git command.

I have install xltrails without a problem.  I have recently uninstalled xltrails but that did not correct the xl install problem

suggestions?

**Comment by fzumstein** [comment]
When you go to Control Panel > Programs > Programs and Features, do you see `Git XL version 0.4.1` in the list?

**Comment by CharlesRHall** [comment]
Yes I do

 

--Charlie

**Comment by fzumstein** [comment]
I would uninstall Git XL and then re-install from scratch, I couldn't replicate the issues here.

**Comment by CharlesRHall** [comment]
I also have xltrail installed – I have been using it for 8 months – the xl documentation says they can coexist but maybe they cannot?  Or maybe there is an order to the install process.  I also have sourcetree installed.  Should I uninstall everything, and then start with installing xl?

 

--Charlie

**Comment by fzumstein** [comment]
There seems to be some confusion: `Git XL` was formerly (before v0.4.0) called `git-xltrail`. You should only have either `Git XL` or the old `git-xltrail` installed, they can't co-exist.

Now, what you probably refer to is that `Git XL` can be used alongside with `xltrail`. By that we mean the web application under www.xltrail.com. Renaming this project here into `Git XL` was exactly for that reason, to stop the confusion between `xltrail`, the web tool and `Git XL`, the local Git extension.

**Comment by CharlesRHall** [comment]
Thanks – that has resolved my issues

 

--Charlie
