### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by inscara** [xlwings/git-xl#52]
Hi,

Can you give step-by-step instructions on how to install git xl from source? 

Thanks!

**Comment by fzumstein** [comment]
Hi, would you be able to share your motivation for doing this? thanks!

**Comment by inscara** [comment]
Hi, thanks. Yes, I'm working in a University network and the execution of EXE files is blocked by administration policies. It would be convenient to have a way to install the tool for a local user without bothering any administrator.

**Comment by fzumstein** [comment]
I am not sure if building from source will be less painful, to be honest. In theory, you'd need to build the executables like it's done in the CI script: https://github.com/xlwings/git-xl/blob/master/appveyor.yml#L29-L41

Then place them in the right folders according to what the InnoInstaller does: https://github.com/xlwings/git-xl/blob/master/scripts/windows/inno-setup-git-xl-installer.iss

**Comment by inscara** [comment]
Thanks! I will take a look at it.

**Comment by fzumstein** [comment]
See: https://github.com/xlwings/git-xl/blob/master/BUILDING.md
