### ISSUE TITLE
git diff doesn't work in Parallels windows environment

### ISSUE THREAD

**Issue by MasterSergius** [xlwings/git-xl#54]
I'm working on Mac and the only one to work well with VBA for excel - use some Windows environment. I've decided to use Parallels Desktop (kinda of virtualization software) with Windows 10 on my Mac.
Command `git xl ls-files` - works perfectly, but `git diff` says only "files differ" and that's all.

**Comment by fzumstein** [comment]
Hi, this won't have anything to do with Parallels. Are you sure that you enabled Git XL after running the installer application? You need to run either `git xl install` or `git xl install --local`.

**Comment by MasterSergius** [comment]
Yes, I performed git xl install, otherwise how it is supposed to list all files:
```
$ git xl ls-files

./test_wb.xlsm
    VBA/Document/Thisworkbook
    VBA/Document/Sheet1
    VBA/Module/Module1
```

**Comment by fzumstein** [comment]
`git xl ls-files` will work after running the graphical installer without any further steps. To use the diff, you will additionally need to run `git xl install --local` or `git xl install` on a command prompt wich will register Git XL as the differ.

**Comment by MasterSergius** [comment]
Hmm, suddenly it started to work after local install, interesting, probably, let's close this issue
