### ISSUE TITLE
change branch does not update my excel file (while opened)

### ISSUE THREAD

**Issue by richipower** [xlwings/git-xl#56]
hello! i am very happy that i can use this to work with my excel files. I mostly use it for macros, now when i have my excel code in VBA i see the differences but lets say if i am in dev_branch and make changes there (and leave my excel open) then commit and then i want to change to the master branch, the files that i made to the dev_branch appear as uncommited to the master branch and i cannot discard them directly, i need to close excel and open it again...
Is there a way to enhance this? like when working with .cpp files or so? that they automatically update without needing to close the file and open it again?

**Comment by fzumstein** [comment]
Git needs to change the files but can't do so as Excel is blocking them, so no, there's no  easy way.
