### ISSUE TITLE
Git XL is not really open source

### ISSUE THREAD

**Issue by anders-code** [xlwings/git-xl#57]
There's no law that Git XL has to be open source, but if it isn't it probably shouldn't claim to be.

I tried to install from source and immediately discovered that it's a thin python wrapper around a binary xltrail-core.dll checked into git in the src directory.

This has huge security and portability issues:
- I would have loved to port it to my OS of choice
- was interested in using it in an environment where we need to audit all dependencies. I had to reject it immediately due to this issue.
- Individuals should be able to audit their tools to ensure they don't contain spyware and adware. Opening the source gives a lot of instant trust and transparency.
- there can't really be meaningful community contribution when we can't make changes. It's better to get a pull-request with a fix than just a complaint.

Please consider making the missing sources to xltrail-core.dll, or at least the necessary parts, available!

If that is not feasible please consider clarifying statements like these:
- "Git XL is an open-source wrapper **for a proprietary binary Windows DLL that provides a** Git command line extension for managing Excel workbook files in Git." 
- "It is written in Python **except for the proprietary dll part**"

Windows users that just want to download a binary that works probably don't understand or care about the distinction between "Freeware" and open source software. If this is the target group for your product, it wouldn't seem to matter much to them. But the users like me that would really appreciate that you provided this as open source are likely to be disappointed, suspicious, or offended. So there would appear no net benefit to a misleading claim.

It seems like your group genuinely appreciates and supports open source, and I assume that it is not the intention to mischaracterize anything and there's nothing wrong with being closed source if that's the best business case.

I appreciate your consideration.

**Comment by fzumstein** [comment]
Hey @anders-code, thanks for pointing this out and you're right, it's a massive "oversight" that slipped in with the 0.2.0 release. It was correct for the original 0.1.0 release, so you might want to check this one out in the meantime.
The issue is that the dll is based on a 3rd party commercial product that we can't open-source, so I will adjust the license to reflect that properly.
Further down the road, we might look into getting rid again of that dependency so we can properly open-source it again.
What platform are you on? macOS?

**Comment by fzumstein** [comment]
We actually decided to go the other way round, i.e. getting back to fully open-source by removing the merge feature for now. will post more info in the release notes.

**Comment by anders-code** [comment]
@fzumstein Awesome! I'm on Linux mostly. No idea if this will work or not but I'll take another look. Thank you.
