### ISSUE TITLE
[Feature Request] Support diffing of the actual worksheet content

### ISSUE THREAD

**Issue by pascalbe-dev** [xlwings/git-xl#61]
Thanks for the tool. 
I was wondering, if it is still on the roadmap to support diffing the content of the actual worksheet as noted in [this article](http://dailydoseofexcel.com/archives/2018/05/02/excel-version-control-with-git/). 

It would be great, if we had a meaningful diff for the content of the worksheet (no VBA).

**Comment by fzumstein** [comment]
We had to take a step back here as we wanted to make things truly open source, see: https://github.com/xlwings/git-xl/issues/57 so it's not something we plan to add in the immediate future. In the meantime, you can always try out https://www.xltrail.com that will show you the diffs of the sheets.

**Comment by pascalbe-dev** [comment]
Okay. Thanks for the info. Should we keep this issue open then?

**Comment by fzumstein** [comment]
I'll close it for now, we can always revisit later. Thanks!
