### ISSUE TITLE
Git diff Returns No Output For .xlsx & .xlsb Formats

### ISSUE THREAD

**Issue by kharithomas** [xlwings/git-xl#67]
Installed git xl per the instructions but I'm not seeing any output. Is this related to the current build failing or does the tool only support VBA code?

![image](https://user-images.githubusercontent.com/55037984/138142020-120727e9-1824-4e61-bbf1-1b565c2ef6d8.png)

**Comment by fzumstein** [comment]
Nothing to do with the failing build, no, but I can't actually test it locally, as I am running into this issue: https://github.com/xlwings/git-xl/issues/65

**Comment by lubaxe** [comment]
@fzumstein I believe my PR addresses this issue, by updating to the new oletools and newest version of python. The pipeline fails due to the cert issue. I have tested it locally with office 365 .xlsb files.

**Comment by fzumstein** [comment]
this is now released with 0.5.1
