### ISSUE TITLE
Just outright doesn't work at all

### ISSUE THREAD

**Issue by Gaibhne** [xlwings/git-xl#76]
I added an Excel file, committed, made some changes, committed again and used `git diff`, and it shows nothing about the change at all (but does detect that there is a change):

```
C:\Users\Me\Documents\Stuff>git diff 13e4f32..3fc2f84
diff --xl a/Finanzen_010.xlsx b/Finanzen_010.xlsx
```

No further output is generated. I tried all the various advised ways of installing (locally, globally, with `install xl` and `install xltrail`), the given `git xl install` seemed to work fine, at least it reported no errors, and I am guessing that output with `diff --xl` shows that it is working behind the scenes, just not generating any output.

**Comment by Gaibhne** [comment]
After some further research, the output seems to be affected by having something that provides a `diff` executable installed, so I suspect `git-xl` somehow depends on having a particular other software installed that provides that. My Windows did not come with any `diff` installed, and calling `diff` manually results in `'diff' is not recognized as an internal or external command, operable program or batch file.`.

If that is the case, it would be helpful if the install page mentioned needing to have another software installed.

**Comment by fzumstein** [comment]
it only diffs VBA code.

**Comment by Gaibhne** [comment]
🤦‍♂️ sorry
